In [2]:
import jieba
import json
ary = ['【更新】柯P：洪智坤洩漏公文案還沒看到公文　今處理',
'留洪智坤 柯：殘障求職不易',
'人事處議處洪智坤　柯P：不清楚議處結果']
corpus = []
for title in ary:
    corpus.append(' '.join(jieba.cut(title)))

jieba.add_word('洪智坤',100, 'nr')
print (json.dumps(corpus,ensure_ascii=False))

["【 更新 】 柯 P ： 洪智坤 洩漏 公文 案還 沒 看到 公文 　 今處理", "留 洪智坤   柯 ： 殘障 求職 不易", "人事 處議 處 洪智坤 　 柯 P ： 不 清楚 議處 結果"]


### CountVectorizer

In [10]:
import json
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer() 
X = vectorizer.fit_transform(corpus)
print (type(X))
print (X)
print (vectorizer.inverse_transform(X))  #反轉transform列出原本文本的樣子
print (json.dumps(vectorizer.get_feature_names(),ensure_ascii=False))   #列出文本所有feature原本的樣子

<class 'scipy.sparse.csr.csr_matrix'>
  (0, 4)	1
  (0, 9)	1
  (0, 8)	1
  (0, 3)	2
  (0, 5)	1
  (0, 11)	1
  (0, 2)	1
  (1, 9)	1
  (1, 6)	1
  (1, 7)	1
  (1, 0)	1
  (2, 9)	1
  (2, 1)	1
  (2, 13)	1
  (2, 10)	1
  (2, 14)	1
  (2, 12)	1
[array([u'\u66f4\u65b0', u'\u6d2a\u667a\u5764', u'\u6d29\u6f0f',
       u'\u516c\u6587', u'\u6848\u9084', u'\u770b\u5230',
       u'\u4eca\u8655\u7406'], 
      dtype='<U3'), array([u'\u6d2a\u667a\u5764', u'\u6b98\u969c', u'\u6c42\u8077',
       u'\u4e0d\u6613'], 
      dtype='<U3'), array([u'\u6d2a\u667a\u5764', u'\u4eba\u4e8b', u'\u8655\u8b70',
       u'\u6e05\u695a', u'\u8b70\u8655', u'\u7d50\u679c'], 
      dtype='<U3')]
["不易", "人事", "今處理", "公文", "更新", "案還", "殘障", "求職", "洩漏", "洪智坤", "清楚", "看到", "結果", "處議", "議處"]


### TfidfVectorizer

In [11]:
import json
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer() 
Y = vectorizer.fit_transform(corpus)
print (type(Y))
print (Y)
print (vectorizer.inverse_transform(Y))  #反轉transform列出原本文本的樣子
print (json.dumps(vectorizer.get_feature_names(),ensure_ascii=False))   #列出文本所有feature原本的樣子

<class 'scipy.sparse.csr.csr_matrix'>
  (0, 2)	0.327055479232
  (0, 11)	0.327055479232
  (0, 5)	0.327055479232
  (0, 3)	0.654110958465
  (0, 8)	0.327055479232
  (0, 9)	0.19316423462
  (0, 4)	0.327055479232
  (1, 0)	0.546454011634
  (1, 7)	0.546454011634
  (1, 6)	0.546454011634
  (1, 9)	0.32274454218
  (2, 12)	0.43238508879
  (2, 14)	0.43238508879
  (2, 10)	0.43238508879
  (2, 13)	0.43238508879
  (2, 1)	0.43238508879
  (2, 9)	0.255373598795
[array([u'\u4eca\u8655\u7406', u'\u770b\u5230', u'\u6848\u9084',
       u'\u516c\u6587', u'\u6d29\u6f0f', u'\u6d2a\u667a\u5764',
       u'\u66f4\u65b0'], 
      dtype='<U3'), array([u'\u4e0d\u6613', u'\u6c42\u8077', u'\u6b98\u969c',
       u'\u6d2a\u667a\u5764'], 
      dtype='<U3'), array([u'\u7d50\u679c', u'\u8b70\u8655', u'\u6e05\u695a', u'\u8655\u8b70',
       u'\u4eba\u4e8b', u'\u6d2a\u667a\u5764'], 
      dtype='<U3')]
["不易", "人事", "今處理", "公文", "更新", "案還", "殘障", "求職", "洩漏", "洪智坤", "清楚", "看到", "結果", "處議", "議處"]


### HashingVectorizer

In [5]:
import json
from sklearn.feature_extraction.text import HashingVectorizer
vectorizer = HashingVectorizer() 
Z = vectorizer.fit_transform(corpus)
print (type(Z))
print (Z)
print (vectorizer.inverse_transform(Z))  #error! hash不能反轉!
print (vectorizer.get_feature_names())   #error! hash不能反轉!

<class 'scipy.sparse.csr.csr_matrix'>
  (0, 246441)	0.316227766017
  (0, 492803)	-0.316227766017
  (0, 547271)	0.316227766017
  (0, 664113)	-0.316227766017
  (0, 717058)	0.316227766017
  (0, 982272)	-0.632455532034
  (0, 1034416)	0.316227766017
  (1, 96768)	-0.5
  (1, 104916)	-0.5
  (1, 246441)	0.5
  (1, 576637)	0.5
  (2, 16162)	0.408248290464
  (2, 246441)	0.408248290464
  (2, 377913)	-0.408248290464
  (2, 410670)	-0.408248290464
  (2, 463057)	-0.408248290464
  (2, 569169)	-0.408248290464


AttributeError: 'HashingVectorizer' object has no attribute 'inverse_transform'

### CountVectorizer/TfidfVectorizer/HashingVectorizer/HashingVectorizer+TfidfTransformer
- 四轉將文本轉換為向量的比較，output為: (文本編號, feature編號)     分數

In [27]:
print("=========== CountVectorizer ===========")
print (X)
print("=========== TfidfVectorizer ===========")
print (Y)
print("=========== HashingVectorizer ===========")
print (Z)
print("=========== HashingVectorizer+TfidfTransformer ===========")
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer()
tfidf = transformer.fit_transform(Z)
print (tfidf)

=========== CountVectorizer ===========
  (0, 4)	1
  (0, 9)	1
  (0, 8)	1
  (0, 3)	2
  (0, 5)	1
  (0, 11)	1
  (0, 2)	1
  (1, 9)	1
  (1, 6)	1
  (1, 7)	1
  (1, 0)	1
  (2, 9)	1
  (2, 1)	1
  (2, 13)	1
  (2, 10)	1
  (2, 14)	1
  (2, 12)	1
=========== TfidfVectorizer ===========
  (0, 2)	0.327055479232
  (0, 11)	0.327055479232
  (0, 5)	0.327055479232
  (0, 3)	0.654110958465
  (0, 8)	0.327055479232
  (0, 9)	0.19316423462
  (0, 4)	0.327055479232
  (1, 0)	0.546454011634
  (1, 7)	0.546454011634
  (1, 6)	0.546454011634
  (1, 9)	0.32274454218
  (2, 12)	0.43238508879
  (2, 14)	0.43238508879
  (2, 10)	0.43238508879
  (2, 13)	0.43238508879
  (2, 1)	0.43238508879
  (2, 9)	0.255373598795
=========== HashingVectorizer ===========
  (0, 246441)	0.316227766017
  (0, 492803)	-0.316227766017
  (0, 547271)	0.316227766017
  (0, 664113)	-0.316227766017
  (0, 717058)	0.316227766017
  (0, 982272)	-0.632455532034
  (0, 1034416)	0.316227766017
  (1, 96768)	-0.5
  (1, 104916)	-0.5
  (1, 246441)	0.5
  (1, 576637)	0.5


### CountVectorizer/TfidfVectorizer/HashingVectorizer/HashingVectorizer+TfidfTransformer
- toarray(): 此例為三個文本，output為三個文本各自佔有feature的分數矩陣

In [26]:
print("=========== CountVectorizer ===========")
print (X.toarray())
print("=========== TfidfVectorizer ===========")
print (Y.toarray())
print("=========== HashingVectorizer ===========")
print (Z.toarray())
print("=========== HashingVectorizer+TfidfTransformer ===========")
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer()
tfidf = transformer.fit_transform(Z)
print (tfidf.toarray())
print "array type: ",type(X.toarray())

=========== CountVectorizer ===========
[[0 0 1 2 1 1 0 0 1 1 0 1 0 0 0]
 [1 0 0 0 0 0 1 1 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 1 1 0 1 1 1]]
=========== TfidfVectorizer ===========
[[ 0.          0.          0.32705548  0.65411096  0.32705548  0.32705548
   0.          0.          0.32705548  0.19316423  0.          0.32705548
   0.          0.          0.        ]
 [ 0.54645401  0.          0.          0.          0.          0.
   0.54645401  0.54645401  0.          0.32274454  0.          0.          0.
   0.          0.        ]
 [ 0.          0.43238509  0.          0.          0.          0.          0.
   0.          0.          0.2553736   0.43238509  0.          0.43238509
   0.43238509  0.43238509]]
=========== HashingVectorizer ===========
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
=========== HashingVectorizer+TfidfTransformer ===========
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  

### get_feature_names( ):CountVectorizer/TfidfVectorizer
- 兩者因為算法不同，所以順序會不太一樣

In [25]:
print("=========== CountVectorizer ===========")
print (json.dumps([u'\u66f4\u65b0', u'\u6d2a\u667a\u5764', u'\u6d29\u6f0f',
       u'\u516c\u6587', u'\u6848\u9084', u'\u770b\u5230',
       u'\u4eca\u8655\u7406'],ensure_ascii=False))
print (json.dumps([u'\u6d2a\u667a\u5764', u'\u6b98\u969c', u'\u6c42\u8077',
       u'\u4e0d\u6613'],ensure_ascii=False))
print (json.dumps([u'\u6d2a\u667a\u5764', u'\u4eba\u4e8b', u'\u8655\u8b70',
       u'\u6e05\u695a', u'\u8b70\u8655', u'\u7d50\u679c'],ensure_ascii=False))
print("=========== TfidfVectorizer ===========")
print (json.dumps([u'\u4eca\u8655\u7406', u'\u770b\u5230', u'\u6848\u9084',
       u'\u516c\u6587', u'\u6d29\u6f0f', u'\u6d2a\u667a\u5764',
       u'\u66f4\u65b0'],ensure_ascii=False))
print (json.dumps([u'\u4e0d\u6613', u'\u6c42\u8077', u'\u6b98\u969c',
       u'\u6d2a\u667a\u5764'],ensure_ascii=False))
print (json.dumps([u'\u7d50\u679c', u'\u8b70\u8655', u'\u6e05\u695a', u'\u8655\u8b70',
       u'\u4eba\u4e8b', u'\u6d2a\u667a\u5764'],ensure_ascii=False))

=========== CountVectorizer ===========
["更新", "洪智坤", "洩漏", "公文", "案還", "看到", "今處理"]
["洪智坤", "殘障", "求職", "不易"]
["洪智坤", "人事", "處議", "清楚", "議處", "結果"]
=========== TfidfVectorizer ===========
["今處理", "看到", "案還", "公文", "洩漏", "洪智坤", "更新"]
["不易", "求職", "殘障", "洪智坤"]
["結果", "議處", "清楚", "處議", "人事", "洪智坤"]


### FeatureHasher
- hasher = FeatureHasher(n_features=10): 後面hasher.fit_transform()要丟list(dictionay)
- hasher = FeatureHasher(n_features=10,input_type="string"): 後面hasher.fit_transform要丟list(string)

In [13]:
from sklearn.feature_extraction import FeatureHasher
hasher = FeatureHasher(n_features=10)
featureHasher=hasher.fit_transform([{'a':1,'b':2},{'c':3,'d':4}])
print ("featureHasher: ")
print (featureHasher)
print (type(featureHasher))

featureHasher: 
  (0, 0)	1.0
  (0, 1)	-2.0
  (1, 7)	-3.0
  (1, 9)	4.0
<class 'scipy.sparse.csr.csr_matrix'>


### 'scipy.sparse.csr.csr_matrix' v.s. 'numpy.ndarray'

In [24]:
# from 'numpy.ndarray' to 'scipy.sparse.csr.csr_matrix' 
from scipy import sparse
print "=========== scipy.sparse.csr.csr_matrix ============",
print sparse.csr_matrix(X.toarray())   

# from 'scipy.sparse.csr.csr_matrix' to 'numpy.ndarray'
print "============= numpy.ndarray ==============",
print X.toarray()

=========== scipy.sparse.csr.csr_matrix ============   (0, 2)	1
  (0, 3)	2
  (0, 4)	1
  (0, 5)	1
  (0, 8)	1
  (0, 9)	1
  (0, 11)	1
  (1, 0)	1
  (1, 6)	1
  (1, 7)	1
  (1, 9)	1
  (2, 1)	1
  (2, 9)	1
  (2, 10)	1
  (2, 12)	1
  (2, 13)	1
  (2, 14)	1
============= numpy.ndarray ============== [[0 0 1 2 1 1 0 0 1 1 0 1 0 0 0]
 [1 0 0 0 0 0 1 1 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 1 1 0 1 1 1]]
